name: Publish Chatwoot CE docker images
on:
  push:
    branches:
      - develop
      - master
    tags:
      - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_REF: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}
      
      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      
      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
      
      - name: Strip enterprise code
        run: |
          rm -rf enterprise
          rm -rf spec/enterprise
      
      - name: Set Chatwoot edition
        run: |
          echo -en '\nENV CW_EDITION="ce"' >> docker/Dockerfile
      
      - name: Set docker tag
        run: |
          echo "DOCKER_TAG=porameht/chatwoot:$GIT_REF-ce" >> $GITHUB_ENV
      
      - name: Replace docker tag if master
        if: github.ref_name == 'master'
        run: |
          echo "DOCKER_TAG=porameht/chatwoot:latest-ce" >> $GITHUB_ENV
      
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file docker/Dockerfile \
            --tag ${{ env.DOCKER_TAG }} \
            --push \
            .
